language: php
php:
    - 5.4
    - 5.5

before_script:
    - composer update --prefer-source --dev

script:
    - bin/phpspec status
    - bin/phpspec run -fpretty

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/dd240af232144434bff2
        on_success: always  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
