language: php
php:
    - 5.3
    - 5.3.3
    - 5.4
    - 5.5

before_script:
    - composer install --prefer-source

notifications:
    email:
        - plazanet.pierre@gmail.com
script:
    - bin/phpspec -fpretty
